### PR TITLE
Replace core serializer

### PR DESCRIPTION
**Pull request by Scooletz**
Solving #29

### CODE REVIEW

**Comment by Scooletz** [comment]
This PR makes the core serializers & ASQ serializations totally separated. I'd like to point at:

1.  the configuration being done for Acceptance Tests, where I explicitly override any serialization for `MessageWrapper` if it's different from `Xml` or `JSON`. This leaves serializer related tests working (they handle properly body of the messages), still using JSON for `MessageWrapper`. If you have any better solution, please do share.

1. The mutator test, lost its body overload. As the tests touches headers only, this should be just fine.

Default setting for tests can be seen below
```
public Task Configure(BusConfiguration configuration, IDictionary<string, string> settings)
{
    connectionString = settings["Transport.ConnectionString"];
    configuration.UseSerialization<JsonSerializer>();
    configuration.UseTransport<AzureStorageQueueTransport>()
        .ConnectionString(connectionString)
        .MessageInvisibleTime(TimeSpan.FromSeconds(5))
        .SerializeMessageWrapperWith(defintion => MessageWrapperSerializer.Json.Value)
        .CreateSendingQueues();

    return Task.FromResult(0);
}
``

**Comment by Scooletz** [comment]
Ping @Particular/azure-maintainers . I'm looking forward to seeing your remarks about this PR. If you find it's ok, please merge. I needed to bump up the core, but this is a separate commit.

**Comment by Scooletz** [comment]
Thank you @SeanFeldman ! :)
I've updated all the mentioned above, including the connection string. I needed to resolve properly reference to `System.Special` (it wasn't bumped up properly before) & removed a few double disposals as well.

Ping @Particular/azure-maintainers

**Comment by yvesgoeleven** [comment]
Great work! Merged it in!

**Pull request merged**
