### PR TITLE
Add FailedQ and exception headers when delayed delivery fails to dispatch

### PR DESCRIPTION
**Pull request by mauroservienti**
When the delayed delivery feature fails to dispatch a delayed message the message is immediately moved to the error queue. Fault management headers are not added to the message making it impossible to retry the failed message. This PR adds the FailedQ header and the exception details headers to the failed message before moving it to the configured error queue.

### CODE REVIEW

**Comment by timbussmann** [comment]
is there a way to test this? e.g. an acceptance test sending a delayed message to a queue that does not exist?

Does the current version handle this correctly or is this actually a bug fix?

**Comment by mauroservienti** [comment]
the current version doesn't handle this at all. I guess I can come up with a test.

**Comment by timbussmann** [comment]
> the current version doesn't handle this at all. I guess I can come up with a test.

Is this something we should merge to master afterwards then (and potentially backport)?

**Comment by mauroservienti** [comment]
> > the current version doesn't handle this at all. I guess I can come up with a test.
> 
> Is this something we should merge to master afterwards then (and potentially backport)?

Yes, sure. The change doesn't depend on the new transport seam. We can also leave this PR here and raise an issue to be tackled in a future maintenance release. The fix here addresses an extremely rare scenario.

**Review by tmasternak — APPROVED** [review]

**Review by SeanFeldman — APPROVED** [review]

**Comment by tmasternak** [comment]
@mauroservienti does this need a rebase?

**Comment by mauroservienti** [comment]
I'm pretty sure it's simpler to recreate the PR, the relevant changes are in the `src/Transport/DelayDelivery/DelayedMessagesPoller.cs` file.

**Comment by tmasternak** [comment]
@mauroservienti was this part of the enhancement release? I'm trying to figure out how to make sure this is not lost.

**Comment by mauroservienti** [comment]
> @mauroservienti was this part of the enhancement release? I'm trying to figure out how to make sure this is not lost.

No, I raised it in the context of the new transport seam. Do you want me to recreate this PR against `master`? (Not willing to rebase ☠️😅)

**Comment by tmasternak** [comment]
@mauroservienti If you can recreate the PR I can do the smoke testing.

**Comment by mikeminutillo** [comment]
Recreated here https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/650

**Pull request closed without merging**
