### PR TITLE
Graceful shutdown for poller

### LINKED ISSUE #318: Core 6: Error at shutdown WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller Failed at spinning the poller
I sometimes get the following error during endpoint shutdown which I think should should be gracefully handled.

```
2018-01-29 09:20:51.804 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller Failed at spinning the poller
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<SpinOnce>d__20.MoveNext() in C:\BuildAgent\work\956312761da410d2\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<InnerPoll>d__17.MoveNext() in C:\BuildAgent\work\956312761da410d2\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 101
```

### PR DESCRIPTION
**Pull request by danielmarbach**
Replaces #317 
Closes #318 

also removes unnecessary settings access

### CODE REVIEW

**Comment by danielmarbach** [comment]
Should we release a patch for the 7.5.x version range?

**Comment by SeanFeldman** [comment]
Has this work been approved by PD? :trollface: 
👍 to release as 7.5.4 and also to port forward.

**Comment by timbussmann** [comment]
> Should we release a patch for the 7.5.x version range?

not sure these changes really justify backporting?

**Comment by danielmarbach** [comment]
There is no hard reason to do it @timbussmann I was just thinking it is a low effort / risk change that would make the world slightly better (TM) ;)

**Pull request merged**
