### PR TITLE
Remove beta tag

### PR DESCRIPTION
**Pull request by SeanFeldman**
Prepare ASQ release branch

### CODE REVIEW

**Review by danielmarbach — APPROVED** [review]

**Comment by danielmarbach** [comment]
Would it make sense before we release to add diagnostic sections?

**Comment by SeanFeldman** [comment]
I'll make it a draft until the diagnostics section is done.

**Comment by SeanFeldman** [comment]
Requires diagnostics section PR (#484) to be merged first

**Comment by SeanFeldman** [comment]
Requires option connection string PR (#493) to be merged before this can go.

**Review by lailabougria — APPROVED** [review]

**Pull request merged**
