### PR TITLE
cache JsonSerializer in TimeoutEntity and add newtonsoft dependency

### LINKED ISSUE #178: TimeoutEntity questions
```
    class TimeoutEntity : TableEntity
    {
        public string Destination { get; set; }
        public byte[] Body { get; set; }
        public string MessageId { get; set; }
        public string Headers { get; set; }
        
        static string Serialize<T>(T obj)
        {
            var sw = new StringWriter();
            new JsonSerializer().Serialize(sw, obj);
            sw.Flush();
            return sw.ToString();
        }

        static T Deserialize<T>(string obj)
        {
            return new JsonSerializer().Deserialize<T>(new JsonTextReader(new StringReader(obj)));
        }
```

 * `new JsonSerializer()` is an expensive operation. and this is on the fast path? So i assume JsonSerializer should be cached?
 * if we explicitly use json .net (ie not an inferred nuget dependency) then it needs to be a nuget dependency in our spec. if we dont, changes in upstream packages in the future could result in no json .net referenced
 * why are we using disposbale stuff and not putting them in a using

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #178

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers thoughts?

**Comment by SimonCropp** [comment]
But pr means nothing after a merge. Only the commits matter.

**Comment by danielmarbach** [comment]
See https://github.com/Particular/NServiceBus.Persistence.AzureStorage/pull/127

**Comment by Scooletz** [comment]
@danielmarbach it's marked as `Accepted` so I'm leaving it for you to merge.

**Pull request merged**
