### PR TITLE
ToTransportAddress uses dash instead of dot for qualifier

### PR DESCRIPTION
**Pull request by danielmarbach**
Addresses #279

### CODE REVIEW

**Comment by danielmarbach** [comment]
Ping @Particular/azure-maintainers

**Comment by danielmarbach** [comment]
This should be a fairly safe switch to do right? Because the '.' based queues would anyway not work

**Comment by SeanFeldman** [comment]
@danielmarbach agreed. It would throw at runtime.

**Comment by yvesgoeleven** [comment]
Can we run a test with the backward compat sanitization logic https://docs.particular.net/transports/azure-service-bus/sanitization?version=asb_8#automated-sanitization-backward-compatibility-with-versions-6-and-below before and after applying this change and see if the generated guids are still the same?

**Comment by SeanFeldman** [comment]
@yvesgoeleven I assume your question is covered by #282 and doesn't need to be answered here 🙂

**Pull request merged**
