### PR TITLE
Internalize UseNativeTimeouts 

### PR DESCRIPTION
**Pull request by Scooletz**
This PR makes Native Timeouts internaliz till doco and migration arrives.

### CODE REVIEW

**Comment by Scooletz** [comment]
Ping @Particular/azure-maintainers

**Comment by danielmarbach** [comment]
Short question: Have you considered internals visible to attribute for the acceptance tests? What drove you to use reflection? Not saying one is better than the other, just want to understand the reasoning

**Comment by SeanFeldman** [comment]
@danielmarbach we never expose internals to the ATTs project since it's supposed to be treated as if it was production code. I might be off on this.

**Comment by Scooletz** [comment]
Yes @danielmarbach I considered it but had some problems with making it work. This just works and is a quick way of hiding it for now. No need for `InternalVisibleTo` to make all internals visible.

**Comment by danielmarbach** [comment]
Needs a rebase

**Pull request merged**
