### PR TITLE
Bumping up Fody to enable proper build master

### PR DESCRIPTION
**Pull request by Scooletz**
This is a PR for **master** to fix the Fody build problem. I'm not sure about the `master` quality though.

@Particular/azure-maintainers pls review and comment on.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
> I'm not sure about the master quality though

Same as production & `support-6.2` :) 
Since master contains what the latest support branch has, shouldn't this change go into `support-6.2` and that one into `master`? /cc @yvesgoeleven

**Comment by yvesgoeleven** [comment]
due to the way gitflowversion works, wouldn't that cause a loss of a minor version? I'd say leave it failing until we have another hotfix or so?

**Comment by Scooletz** [comment]
The only reason I've brought this to the table is the TeamCity dependency of Azure Storage Persistenc which disables the ability to build it properly. What would be your proposal for providing these artifacts for the build, or, answering a more general question, enable ASP to build properly?

/cc @dbelcham

**Comment by Scooletz** [comment]
Closing as @dbelcham is creating a separate branch for ASP tests purposes.

**Pull request closed without merging**
