### PR TITLE
[WIP]Spike native pub sub

### PR DESCRIPTION
**Pull request by andreasohlund**
Connects to #277 

Switching the transport to native pubsub storing subscription details in table storage.

This is just a hack to prove that it works

### CODE REVIEW

**Comment by andreasohlund** [comment]
The 4 failing tests https://builds.particular.net/viewLog.html?buildId=208232&buildTypeId=NServiceBus_Transports_NServiceBusAzureStorageQueues_1Build is related to multi inheritance but that should be easy to fix

**Comment by andreasohlund** [comment]
@Particular/azure-maintainers my idea was a mixed mode option so that we can keep the current message driven pubsub for backwards compatibility but new users could use this new simpler approach?

**Comment by SeanFeldman** [comment]
@andreasohlund like the idea.

**Comment by andreasohlund** [comment]
@SzymonPobiega @timbussmann ideas on how to support mixed mode, how to deal with [`IMessageDrivenSubscriptionTransport`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/IMessageDrivenSubscriptionTransport.cs)

**Comment by Scooletz** [comment]
We're moving more and more to this storage account of ASQ. Good 👍

**Comment by andreasohlund** [comment]
I didn't know the native timeouts where already in https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/161 but since that has happened this PR would mean ASQ no longer have a hard dep on ASP to work properly?

**Comment by Scooletz** [comment]
They were, but they are not in public API as we need to provide:
- doco
- migration
- review the code again.

Once we have it, yes, beside sagas, we need no storage.

**Comment by andreasohlund** [comment]
Do we want to proceed with this? (if yes that I'll get the caching and config options in)

**Comment by SeanFeldman** [comment]
It's marked as in-progress, so I've assigned it to you (since you're the originator of the PR).

> Do we want to proceed with this?
Depends who you ask 😉

**Comment by SeanFeldman** [comment]
@boblangley will raise an issue in PlatDev for this (pub/sub) and native timeouts.

**Comment by SeanFeldman** [comment]
@andreasohlund was this spike supposed to go into transport v8?

**Comment by andreasohlund** [comment]
Was just trying to prove that it was a low hanging fruit. I guess it can be added in any minor version but deprecating support for message driven pub sub would have to wait.

In short: This can wait until the netcore version is released IMO

**Comment by SeanFeldman** [comment]
Closing this for now. Please reopen when and if it becomes relevant again.

**Pull request closed without merging**
