### PR TITLE
SetUpFixture fix up

### PR DESCRIPTION
**Pull request by Scooletz**
[SetUp] changed to [OneTimeSetup]
according to https://github.com/nunit/docs/wiki/SetUpFixture-Attribute

### CODE REVIEW

**Comment by Scooletz** [comment]
Ping @Particular/azure-storage-queues-maintainers

**Comment by SeanFeldman** [comment]
`When_saga_id_changed.Should_throw` will fail until a fix that was done to the ATTs is release (core next beta). I had to disable it until next core update will re-enable it again.

**Comment by SimonCropp** [comment]
@Scooletz sorry i must have missed this one. 

I pushed a ignore for When_saga_id_changed.Should_throw

**Comment by SimonCropp** [comment]
@Scooletz assuming we have a green build the diff looks good

**Comment by SimonCropp** [comment]
@Particular/azure-storage-queues-maintainers review and merge please

**Comment by Scooletz** [comment]
As I've initiated this PR, I'm looking forward to other @Particular/azure-storage-queues-maintainers to chine in :)

**Comment by SeanFeldman** [comment]
Looks good. It's a wip though, so no idea if still being worked on or not.

**Comment by SeanFeldman** [comment]
image

**Comment by Scooletz** [comment]
It's no longer WIP.

**Comment by SeanFeldman** [comment]
Merged

**Pull request merged**
