### PR TITLE
Update refs

### PR DESCRIPTION
**Pull request by SimonCropp**
replaces https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/170

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@SimonCropp just to make sure, did you have a chance to smoke test with storage v8?

**Comment by SimonCropp** [comment]
@SeanFeldman not yet. i wanted to see what the build server said

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers i think this is ready for a review

**Comment by boblangley** [comment]
Merged #177

**Pull request merged**
